insert into person(id,username,password,name,email, role, country) values(1,"admin","$2y$12$ExGQ6RmZ8oJRX73Yr.IU.enhKwvW579defyjmCn5Vi85XDXVLVYwm","Jelena Pejičić","jelenapejicic2008@hotmail.com",1,"RS"); --inkvizitor123
insert into person(id,username,password,name,email, role, country) values(2,"admin1","$2y$12$ExGQ6RmZ8oJRX73Yr.IU.enhKwvW579defyjmCn5Vi85XDXVLVYwm","Jelena Pejičić","jelenapejicic2008@hotmail.com",1,"RS"); --inkvizitor123
insert into person(id,username,password,name,email, role, country) values(3,"mladen","$2y$12$ExGQ6RmZ8oJRX73Yr.IU.enhKwvW579defyjmCn5Vi85XDXVLVYwm","Mladen Pejičić","mladenpejicic2008@hotmail.com",0,"RS"); --inkvizitor123

insert into question(id,category,date,text,question_type,answer,num_of_answers,path,points) values(1,0,"2020-02-02","Koja valuta se koristi u Japanu?",0,"jen",1,"",2);
insert into question(id,category,date,text,question_type,answer,num_of_answers,path,points) values(2,0,"2020-02-02","Čija kost se koristi za oštrenje zuba kućnih ljubimaca?",0,"sipina",1,"",2);
insert into question(id,category,date,text,question_type,answer,num_of_answers,path,points) values(3,0,"2020-02-02","Kako se zove španski ples koju u prevodu znači dvokorak?",0,"paso doble",1,"",2);
insert into question(id,category,date,text,question_type,answer,num_of_answers,path,points) values(4,0,"2020-02-02","Navedite prezime američkog predsednika koji je dao ostavku zbog afere Votergejt?",0,"Nikson",1,"",2);
insert into question(id,category,date,text,question_type,answer,num_of_answers,path,points) values(5,0,"2020-02-02","Navedite broj članica EU koje koriste evro kao valutu?",0,"19",1,"",2);
insert into question(id,category,date,text,question_type,answer,num_of_answers,path,points) values(6,7,"2020-02-02","Navedite izvođača i naziv pjesme?",5,"The Weeeknd,Blinding Lights",2,"TheWeekndBlindingLights.mp3",1);